version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - revive
    - unconvert

  settings:
    revive:
      severity: error
      enable-default-rules: true
      rules:
        - name: exported

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
