upstream uos_api_backend {
    server unix:/data/unifi-core/config/http/uos-http.sock;
}

upstream uos_auth_backend {
    server unix:/data/unifi-core/config/http/uos-http.sock;
}

upstream uos_agent_api_backend {
    server unix:/data/unifi-core/config/http/uos-http.sock;
}
