// Package payload keeps controller-facing JSON keys and renderer enums
// consistent across switch and gateway builders.
package payload

const (
	jsonKeyAddress     = "address"
	jsonKeyAutoneg     = "autoneg"
	jsonKeyEnable      = "enable"
	jsonKeyFullDuplex  = "full_duplex"
	jsonKeyIfName      = "ifname"
	jsonKeyIsUplink    = "is_uplink"
	jsonKeyL1Up        = "l1up"
	jsonKeyLatency     = "latency"
	jsonKeyMAC         = "mac"
	jsonKeyMACTable    = "mac_table"
	jsonKeyMaxSpeed    = "max_speed"
	jsonKeyMedia       = "media"
	jsonKeyName        = "name"
	jsonKeyNetworkGrp  = "networkgroup"
	jsonKeyNetmask     = "netmask"
	jsonKeyNumPort     = "num_port"
	jsonKeyPortIdx     = "port_idx"
	jsonKeyRXBytes     = "rx_bytes"
	jsonKeyRXBytesRate = "rx_bytes-r"
	jsonKeyRXErrors    = "rx_errors"
	jsonKeyRXPackets   = "rx_packets"
	jsonKeyRole        = "role"
	jsonKeySpeed       = "speed"
	jsonKeySpeedCaps   = "speed_caps"
	jsonKeySourceIf    = "source_interface"
	jsonKeyTXBytes     = "tx_bytes"
	jsonKeyTXBytesRate = "tx_bytes-r"
	jsonKeyTXErrors    = "tx_errors"
	jsonKeyTXPackets   = "tx_packets"
	jsonKeyType        = "type"
	jsonKeyUp          = "up"
	jsonKeyUptime      = "uptime"

	deviceTypeUSW = "usw"
	deviceTypeUGW = "ugw"
	deviceTypeUXG = "uxg"
	deviceTypeUDM = "udm"
	mediaSFPPlus  = "SFP+"

	gatewayNetworkGroupLAN  = "LAN"
	gatewayNetworkGroupWAN  = "WAN"
	gatewayNetworkGroupWAN2 = "WAN2"
	gatewayPortRoleLAN      = "lan"
	gatewayPortRoleLAN2     = "lan2"
	gatewayPortRoleWAN      = "wan"
	gatewayPortRoleWAN2     = "wan2"
	payloadKindGateway      = "gateway"
	payloadKindSwitch       = "switch"
	payloadModeSwitch       = "switch"
	payloadTypeDHCP         = "dhcp"
)
