package main

import appconfig "github.com/konstruktor1/unifi-stubd/internal/config"

func deviceRuntimeSettings() []runtimeSetting {
	return []runtimeSetting{
		stringSetting("operation-mode", "runtime mode: stub, bridge-observe, observe, port-map, host-direct, or macvlan",
			func(flags *runtimeFlags) *string { return &flags.operationMode },
			func(cfg *appconfig.Config) *string { return &cfg.OperationMode },
		),
		stringSetting("profile", "device profile to emulate; use -list-profiles to show options",
			func(flags *runtimeFlags) *string { return &flags.profileName },
			func(cfg *appconfig.Config) *string { return &cfg.Profile },
		),
		stringSetting("profile-file", "optional external device profile YAML file",
			func(flags *runtimeFlags) *string { return &flags.profileFile },
			func(cfg *appconfig.Config) *string { return &cfg.ProfileFile },
		),
		stringSetting("profile-dir", "optional directory with external device profile YAML files",
			func(flags *runtimeFlags) *string { return &flags.profileDir },
			func(cfg *appconfig.Config) *string { return &cfg.ProfileDir },
		),
		stringSetting("mac", "fake device MAC address, or auto to derive one from hostname and profile",
			func(flags *runtimeFlags) *string { return &flags.macText },
			func(cfg *appconfig.Config) *string { return &cfg.MAC },
		),
		stringSetting("ip", "fake device IPv4 address",
			func(flags *runtimeFlags) *string { return &flags.ipText },
			func(cfg *appconfig.Config) *string { return &cfg.IP },
		),
		stringSetting("hostname", "fake device hostname, or auto to use the OS hostname",
			func(flags *runtimeFlags) *string { return &flags.hostname },
			func(cfg *appconfig.Config) *string { return &cfg.Hostname },
		),
		stringSetting("model", "override UniFi model identifier from the selected profile",
			func(flags *runtimeFlags) *string { return &flags.model },
			func(cfg *appconfig.Config) *string { return &cfg.Model },
		),
		stringSetting("model-display", "override display name from the selected profile",
			func(flags *runtimeFlags) *string { return &flags.modelDisplay },
			func(cfg *appconfig.Config) *string { return &cfg.ModelDisplay },
		),
		stringSetting("firmware-version", "override firmware version from the selected profile",
			func(flags *runtimeFlags) *string { return &flags.version },
			func(cfg *appconfig.Config) *string { return &cfg.Version },
		),
		intSetting("ports", "override number of switch ports from the selected profile",
			func(flags *runtimeFlags) *int { return &flags.portCount },
			func(cfg *appconfig.Config) *int { return &cfg.Ports },
		),
		intSetting("link-speed", "override default switch port speed in Mbps; 0 uses selected profile",
			func(flags *runtimeFlags) *int { return &flags.linkSpeed },
			func(cfg *appconfig.Config) *int { return &cfg.LinkSpeed },
		),
		stringSetting("uplink-speed", "uplink speed in Mbps, auto, or profile",
			func(flags *runtimeFlags) *string { return &flags.uplinkSpeed },
			func(cfg *appconfig.Config) *string { return &cfg.UplinkSpeed },
		),
		intSetting("uplink-port", "override uplink port index; 0 uses selected profile",
			func(flags *runtimeFlags) *int { return &flags.uplinkPort },
			func(cfg *appconfig.Config) *int { return &cfg.UplinkPort },
		),
	}
}
