package main

import appconfig "github.com/konstruktor1/unifi-stubd/internal/config"

func observationRuntimeSettings() []runtimeSetting {
	return []runtimeSetting{
		stringSetting("observe-interface", "host interface used for passive link counters and speed",
			func(flags *runtimeFlags) *string { return &flags.observeInterface },
			func(cfg *appconfig.Config) *string { return &cfg.ObserveInterface },
		),
		stringSetting("observe-bridge", "Linux bridge used for passive FDB MAC table data",
			func(flags *runtimeFlags) *string { return &flags.observeBridge },
			func(cfg *appconfig.Config) *string { return &cfg.ObserveBridge },
		),
		stringSetting("bridge-observe-bridge", "host bridge represented as virtual UniFi switch ports",
			func(flags *runtimeFlags) *string { return &flags.bridgeObserve.Bridge },
			func(cfg *appconfig.Config) *string { return &cfg.BridgeObserve.Bridge },
		),
		stringSetting("bridge-observe-uplink-interface", "bridge member that represents the upstream link",
			func(flags *runtimeFlags) *string { return &flags.bridgeObserve.UplinkInterface },
			func(cfg *appconfig.Config) *string { return &cfg.BridgeObserve.UplinkInterface },
		),
		stringSetting("lldp-source", "passive LLDP source: off or lldpd",
			func(flags *runtimeFlags) *string { return &flags.lldpSource },
			func(cfg *appconfig.Config) *string { return &cfg.LLDPSource },
		),
		stringSetting("traffic-source", "traffic metadata source: off",
			func(flags *runtimeFlags) *string { return &flags.trafficSource },
			func(cfg *appconfig.Config) *string { return &cfg.TrafficSource },
		),
		boolSetting("traffic-rates-enabled", "report read-only interface traffic rates in inform payloads",
			func(flags *runtimeFlags) *bool { return &flags.trafficRatesEnabled },
			func(cfg *appconfig.Config) *bool { return &cfg.TrafficRatesEnabled },
		),
		stringSetting("log-source", "read-only log source: off, journalctl, or syslog",
			func(flags *runtimeFlags) *string { return &flags.logSource },
			func(cfg *appconfig.Config) *string { return &cfg.LogSource },
		),
		stringSetting("proc-source", "read-only proc source: off or procfs",
			func(flags *runtimeFlags) *string { return &flags.procSource },
			func(cfg *appconfig.Config) *string { return &cfg.ProcSource },
		),
		boolSetting("dbus-enabled", "enable optional D-Bus availability checks",
			func(flags *runtimeFlags) *bool { return &flags.dbusEnabled },
			func(cfg *appconfig.Config) *bool { return &cfg.DBusEnabled },
		),
		stringSetting("dbus-bus", "D-Bus bus for optional checks: system or session",
			func(flags *runtimeFlags) *string { return &flags.dbusBus },
			func(cfg *appconfig.Config) *string { return &cfg.DBusBus },
		),
		stringSetting("syslog-path", "syslog file path used by -log-source syslog",
			func(flags *runtimeFlags) *string { return &flags.syslogPath },
			func(cfg *appconfig.Config) *string { return &cfg.SyslogPath },
		),
	}
}
