#!/bin/bash
# UniFi Core HTTP compatibility hooks for the Docker webportal profile.

block_host_mutating_http_endpoints() {
    local site_config="/data/unifi-core/config/http/site-setup.conf"
    local tmp_config

    if [[ ! -f "$site_config" ]] || grep -q "UDM Pro SE lab reset guard" "$site_config"; then
        return
    fi

    # Keep setup/reset API calls observable but non-mutating for this lab image.
    tmp_config="$(mktemp)"
    awk -f "$http_dir/site-setup-api-guard.awk" "$site_config" >"$tmp_config"
    cat "$tmp_config" >"$site_config"
    rm -f "$tmp_config"

    nginx -s reload >/dev/null 2>&1 || true
}

write_lab_http_overrides() {
    local lab_config="/data/unifi-core/config/http/shared-runnable-lab.conf"

    install -m 0644 "$http_dir/shared-runnable-lab.conf" "$lab_config"
    chown unifi-core:unifi-core "$lab_config"
    nginx -s reload >/dev/null 2>&1 || true
}

enable_lab_http_preview() {
    local site_config="/data/unifi-core/config/http/site-local-ip.conf"
    local tmp_config

    if [[ ! -f "$site_config" ]] || grep -q "UDM Pro SE lab HTTP preview" "$site_config"; then
        return
    fi

    # Expose the local preview path while preserving the firmware-owned base
    # nginx config generated by unifi-core.
    tmp_config="$(mktemp)"
    awk -f "$http_dir/site-local-ip-preview.awk" "$site_config" >"$tmp_config"
    cat "$tmp_config" >"$site_config"
    rm -f "$tmp_config"

    nginx -t >/dev/null && nginx -s reload >/dev/null 2>&1 || true
}
