[Service]
Type=simple
Environment=UNIFI_STUBD_VM_UDAPI_USER_CHECK=1
Environment=UNIFI_STUBD_VM_SFP_WAN_PRIMARY=1
ExecStart=
ExecStart=/usr/bin/ubios-udapi-server -c /data/udapi-config/ubios-udapi-server/ubios-udapi-server.state -s /var/run/ubnt-udapi-server.sock -e /var/run/ubnt-udapi-bridge-event.sock -x -t
StandardOutput=journal+console
StandardError=journal+console
